### ISSUE TITLE
Test case pro for first task

### ISSUE THREAD

**Issue by deadlydoge** [fedora-python/pyconcz-challenge#3]
Hi,

thank you for your challange. I suppose, I found some interesting issue for you test cases.
I think, you fogot about recursion depth in Python. Just try append sum of 1000 (range(1,1000)) elemet list.

I wonder, how much success results you will have :) Because all recursion solutions will have wrong results.

Regards,
Dmytro Safonov

**Comment by frenzymadness** [comment]
Hi.

You are right but our private tests contain only lists of numbers smaller that recursion limit so we were accepting solutions with recursion.

If you are curious about an interesting solution without recursion, here is one:

```
def restricted(nums):
    class Total:
        s = 0

        def get_total(self):
            return self.s

    t = Total()
    zipped = zip(nums, [t] * len(nums))

    def add(x):
        number_to_add = x[0]
        t = x[1]

        t.s += number_to_add

    list(map(lambda x: add(x), zipped))

    return t.get_total()
```

**Comment by encukou** [comment]
Not all recursion-based solutions will be wrong – just ones theat recurse deeper for each element of the list :)
```python
def restricted(nums):
    size = len(nums) 
    if size == 0:
        return 0
    elif size == 1:
        return nums[0]
    else:
        return restricted(nums[:size//2]) + restricted(nums[size//2:])
```
